# Generated by Django 4.1.3 on 2022-12-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Account Email')),
                ('password', models.CharField(max_length=100, verbose_name='Hashed Password')),
            ],
        ),
    ]
