# Generated by Django 4.1.3 on 2022-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=4)),
            ],
        ),
    ]
