# Generated by Django 4.1.3 on 2022-12-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobele', '0002_verificationtokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, verbose_name='Account Email'),
        ),
    ]
