# Generated by Django 4.1.3 on 2022-12-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobele', '0003_remove_account_id_account_verified_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerificationTokens',
            new_name='VerificationToken',
        ),
    ]
