# Generated by Django 4.1.3 on 2022-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobele', '0004_rename_verificationtokens_verificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Surname'),
        ),
    ]
