# Generated by Django 4.1.3 on 2022-12-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobele', '0007_country_alter_session_account_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='title',
            new_name='name',
        ),
    ]
