# Generated by Django 4.1.3 on 2022-12-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobele', '0008_rename_title_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
    ]
