# Generated by Django 4.1.3 on 2022-12-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nobele', '0009_rename_city_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobele.account')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobele.country')),
            ],
        ),
    ]
