# Generated by Django 4.1.3 on 2022-12-13 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nobele', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stars', models.IntegerField(verbose_name='Rating')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobele.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobele.country')),
            ],
        ),
    ]
