# Generated by Django 4.1.3 on 2022-12-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TuristicZone',
            new_name='TouristicZone',
        ),
    ]
