# Generated by Django 4.1.3 on 2022-12-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_turisticzone_touristiczone'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristiczone',
            name='trending',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trending'),
        ),
    ]
