# Generated by Django 4.1.3 on 2022-12-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_touristiczone_trending'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TouristicZone',
            new_name='Tour',
        ),
    ]
