# Generated by Django 4.1.3 on 2022-12-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_account_alter_tour_title_veriftokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veriftokens',
            name='id',
        ),
        migrations.AlterField(
            model_name='veriftokens',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.account'),
        ),
        migrations.AlterField(
            model_name='veriftokens',
            name='token',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
