# Generated by Django 4.1.3 on 2022-12-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_veriftokens_id_alter_veriftokens_ip_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifTokens',
            new_name='VerifToken',
        ),
    ]
