# Generated by Django 4.1.3 on 2022-12-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_veriftokens_veriftoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veriftoken',
            name='ip',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
