# Generated by Django 4.1.3 on 2022-12-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_account_id_alter_account_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veriftoken',
            old_name='ip',
            new_name='email',
        ),
    ]
