# Generated by Django 4.1.3 on 2022-12-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_rename_ip_veriftoken_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verif_date',
            field=models.DateField(null=True, verbose_name='Verification Date'),
        ),
    ]
