# Generated by Django 4.1.3 on 2022-12-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_account_verif_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.account')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.tour')),
            ],
        ),
    ]
